Repository ManageIQ/activerecord-id_regions, pull requests merged in 2022-02, with the labels that each got.

#24 Remove Hakiri
  README.md
Labels: developer, cleanup

#25 Use simple testing via ENV variable matrix
  .gitignore
  .travis.yml
  Appraisals
  Gemfile
  activerecord-id_regions.gemspec
  gemfiles/rails_6.0.gemfile
  gemfiles/rails_6.1.gemfile
  spec/spec_helper.rb
Labels: test, rails6.1

#26 version notes
  CHANGELOG.md
  lib/active_record/id_regions/version.rb
Labels: changelog/no, documentation

#27 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .rspec
  .travis.yml
  README.md
  activerecord-id_regions.gemspec
Labels: developer, test

#28 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
